name: pizza_repository
description: The Repo that handles pizzas
publish_to: 'none'
version: 0.0.1

environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # equitable: ^2.0.5
  # firebase_auth: ^4.16.0
  # cloud_firestore: ^4.16.0
  # firebase_storage: ^11.6.0
  # redart: ^0.27.7
  # path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true